name: Run Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 6-14 * * *"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install build

      - name: Run pipeline.py
        run: |
          export PYTHONPATH="$PYTHONPATH:./src"
          python workflows/pipeline.py --TWTR_BEARER_TOKEN "${{ secrets.TWTR_BEARER_TOKEN }}" --TWTR_API_KEY "${{ secrets.TWTR_API_KEY }}" --TWTR_API_KEY_SECRET "${{ secrets.TWTR_API_KEY_SECRET }}" --TWTR_ACCESS_TOKEN "${{ secrets.TWTR_ACCESS_TOKEN }}" --TWTR_ACCESS_TOKEN_SECRET "${{ secrets.TWTR_ACCESS_TOKEN_SECRET }}"

      - name: Checkout repo branch data
        uses: actions/checkout@v2
        with:
          ref: "data"
          token: "${{ secrets.REPO_DATA_TOKEN }}"

      - name: Copy data, and push to repo branch data
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

          git pull origin data

          echo "* $(date) " >> /tmp/tmp.screenshot/update.log
          cp -r /tmp/tmp.screenshot/* .

          git add .
          git commit -m "Upload Data (Cron) $(date)"
          git push origin data
